services:
  gui:
    build: 
      context: ./dad-jokes-gui
      args:
      - SERVICE_URL=http://localhost:8090
    ports:
      - 8080:8080
  service:
    build: ./dad-jokes-service
    ports:
      - 8090:8080
